local Builds = {

    npc_dota_hero_phantom_assassin = {
        "item_stout_shield",
        "item_slippers",
        "item_slippers",
        "item_branches",
        "item_branches",
        "item_blight_stone",
        "item_boots",
        "item_blades_of_attack",
        "item_blades_of_attack",
        "item_circlet",
        "item_magic_stick",
        "item_wraith_band",
        "item_ring_of_basilius",
        "item_mithril_hammer",
        "item_mithril_hammer",
        "item_lesser_crit",
        "item_ogre_axe",
        "item_mithril_hammer",
        "item_recipe_black_king_bar",
        "item_orchid",
        "item_bloodthorn",
        "item_recipe_sange",
        "item_travel_boots",
        "item_basher",
        "item_vanguard",
        "item_recipe_abyssal_blade",
        "item_assault"
    },

    npc_dota_hero_luna = {
        "item_tango",
        "item_slippers",
        "item_circlet",
        "item_recipe_wraith_band",
        "item_boots",
        "item_ring_of_protection",
        "item_sobi_mask",
        "item_boots_of_elves",
        "item_gloves",
        "item_infused_raindrops",
        "item_boots_of_elves",
        "item_boots_of_elves",
        "item_ogre_axe",
        "item_boots_of_elves",
        "item_blade_of_alacrity",
        "item_recipe_yasha",
        "item_ogre_axe",
        "item_mithril_hammer",
        "item_recipe_black_king_bar",
        "item_travel_boots",
        "item_ultimate_orb",
        "item_recipe_manta",
        "item_skadi",
        "item_butterfly"
    },

    npc_dota_hero_axe = {
        "item_tango",
        "item_tango",
        "item_stout_shield",
        "item_ring_of_protection",
        "item_boots",
        "item_ring_of_regen",
        "item_blink",
        "item_chainmail",
        "item_robe",
        "item_broadsword",
        "item_cloak",
        "item_ring_of_health",
        "item_ring_of_regen",
        "item_ring_of_regen",
        "item_branches",
        "item_recipe_headdress",
        "item_recipe_pipe",
        "item_ogre_axe",
        "item_mithril_hammer",
        "item_recipe_black_king_bar",
        "item_travel_boots",
        "item_shivas_guard",
        "item_heart"
    },

    npc_dota_hero_crystal_maiden = {
        "item_tango",
        "item_courier",
        "item_branches",
        "item_branches",
        "item_wind_lace",
        "item_observer_ward",
        "item_observer_ward",
        "item_flying_courier",
        "item_boots",
        "item_ring_of_protection",
        "item_ring_of_regen",
        "item_void_stone",
        "item_staff_of_wizardry",
        "item_recipe_cyclone",
        "item_blink",
        "item_staff_of_wizardry",
        "item_ring_of_regen",
        "item_recipe_force_staff",
        "item_cloak",
        "item_shadow_amulet",
        "item_recipe_glimmer_cape",
        "item_ogre_axe",
        "item_mithril_hammer",
        "item_recipe_black_king_bar",
        "item_sheepstick"
    },

    npc_dota_hero_warlock = {
        "item_tango",
        "item_flask",
        "item_clarity",
        "item_clarity",
        "item_branches",
        "item_branches",
        "item_boots",
        "item_circlet",
        "item_magic_stick",
        "item_arcane_booster",
        "item_arcane_booster",
        "item_ring_of_health",
        "item_recipe_aether_lens",
        "item_point_booster",
        "item_ogre_axe",
        "item_staff_of_wizardry",
        "item_blade_of_alacrity",
        "item_refresher",
        "item_black_king_bar",
        "item_sheepstick"
    }
};

function GetBuild( hero_name )
    return Builds[ hero_name ];
end